export { default as Navbar } from "./Navbar" 
export { default as Cryptocurrencies } from "./Cryptocurrencies" 
export { default as CryptoDetails } from "./CryptoDetails" 
export { default as News } from "./News" 
export { default as Exchanges } from "./Exchanges" 
export { default as Homepage } from "./Homepage" 